"""Runtime BLASST monkeypatch for vLLM 0.25 (does NOT mutate site-packages).

Loaded via sitecustomize.py on PYTHONPATH so it reaches vLLM's spawned EngineCore
workers. When VLLM_BLASST_TAU>0, it reads the installed kernel_unified_attention
source, applies the env-gated BLASST skip (same string patches as
c2/apply_blasst_kernel_patch.py), execs the patched module in-memory, and rebinds
the patched kernel + wrapper into both the ops module and its importer
(triton_attn), so serving uses the sparse decode path. tau=0 => no patch (dense).
"""
import os
import sys

_TAU = float(os.getenv("VLLM_BLASST_TAU", "0") or "0")

_OLD = """        M, L, P, alpha = softmax_step(S, M, L)
        acc = acc * alpha[:, None]

        if SLIDING_WINDOW:
            qpos_lo = q_block_local_idx * BLOCK_Q
            dist = context_len + qpos_lo - seq_offset[:, None]
            if USE_PER_SEQ_CAUSAL:
                is_causal_seq = tl.load(per_seq_causal_ptr + seq_idx)
                sw_mask_v = tl.where(
                    is_causal_seq,
                    dist < SLIDING_WINDOW,
                    (dist < SLIDING_WINDOW) & (dist > -SLIDING_WINDOW),
                )
            elif USE_CAUSAL:
                sw_mask_v = dist < SLIDING_WINDOW
            else:
                sw_mask_v = (dist < SLIDING_WINDOW) & (dist > -SLIDING_WINDOW)
            V = tl.where(sw_mask_v, V, 0.0)
        if USE_PER_TOKEN_HEAD_SCALES:
            # Per-token-head quant: apply v_scale to P instead of V.
            P_v = (P * v_token_head_scales[None, :]).to(V.dtype)
            acc += tl.dot(P_v, V)
        else:
            acc += tl.dot(P.to(V.dtype), V)"""


def _patch_source(src: str) -> str:
    assert "BLASST_TAU" not in src, "already patched"
    src = src.replace("import triton\n",
                      "import triton\nimport os as _os\n_BLASST_TAU = float(_os.getenv('VLLM_BLASST_TAU','0') or '0')\n", 1)
    src = src.replace("    USE_QQ_BIAS: tl.constexpr,  # bool\n",
                      "    USE_QQ_BIAS: tl.constexpr,  # bool\n    BLASST_TAU: tl.constexpr,\n", 1)
    guard = ("        _bl_keep = True\n"
             "        if BLASST_TAU > 0.0:\n"
             "            _bl_keep = tl.max(tl.max(S, axis=1)) >= (tl.min(M) - BLASST_TAU)\n"
             "        if _bl_keep:\n")
    indented = "\n".join(("    " + ln if ln.strip() else ln) for ln in _OLD.split("\n"))
    assert _OLD in src, "loop-block anchor not found (kernel version drift)"
    src = src.replace(_OLD, guard + indented, 1)
    src = src.replace("        USE_QQ_BIAS=use_qq_bias,\n",
                      "        USE_QQ_BIAS=use_qq_bias,\n        BLASST_TAU=_BLASST_TAU,\n", 1)
    return src


def apply() -> None:
    """Rebind the module-global kernel_unified_attention to a BLASST-patched copy that
    lives in a REAL file (serving/v025_blasst/patched_kernel.py, generated by
    build_patched_kernel.py) — so Triton's source parser works. The unmodified wrapper
    looks the kernel up as a module global at call time, so no wrapper surgery is needed;
    the patched kernel's BLASST_TAU defaults to the env tau."""
    if _TAU <= 0:
        return
    import vllm.v1.attention.ops.triton_unified_attention as U
    import patched_kernel  # real-file BLASST kernel (globals pulled from U)
    U.kernel_unified_attention = patched_kernel.kernel_unified_attention
    print(f"[BLASST] installed patched kernel_unified_attention, tau={_TAU} (pid {os.getpid()})", file=sys.stderr, flush=True)
    # C1+C2 path: also patch the TurboQuant per-head decode kernel (_tq_decode_stage1) so
    # TQ4 KV runs BLASST too. per-head program + 1D scores => scalar predicate, no GQA/tile
    # tax => full sparsity, and a skipped block also skips value dequant. No-op when the
    # turboquant backend isn't loaded (bf16 serving) — the patched kernel just isn't called.
    try:
        import vllm.v1.attention.ops.triton_turboquant_decode as TQ
        import turboquant_patched_kernel
        TQ._tq_decode_stage1 = turboquant_patched_kernel._tq_decode_stage1
        print(f"[BLASST] installed patched _tq_decode_stage1 (turboquant), tau={_TAU} (pid {os.getpid()})", file=sys.stderr, flush=True)
    except Exception as _e:
        print(f"[BLASST] turboquant patch skipped: {_e}", file=sys.stderr, flush=True)
